FROM node:19-alpine

ADD https://raw.githubusercontent.com/SaminOz/redis-random-data-generator/master/generator.js https://raw.githubusercontent.com/SaminOz/redis-random-data-generator/master/package.json config.json ./

RUN npm install